Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: handler.LambdaHandler
      CodeUri: D:\DevOps\APITestingBDDApproach
      Runtime: java8.al2
      Architectures:
        - x86_64