version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn package
      - sam deploy
        --template-file template.yml
        --s3-bucket ala123sobhanbucket
        --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml